# Generated by Django 3.2.6 on 2021-08-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prizeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='price')),
                ('date_purchased', models.DateTimeField(auto_now_add=True, verbose_name='date purchased')),
                ('date_taken', models.DateTimeField(blank=True, verbose_name='date purchased')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.prizeclass')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.user')),
            ],
            options={
                'ordering': ['date_purchased'],
            },
        ),
    ]
