# Generated by Django 3.2.6 on 2021-08-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prizeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizeitem',
            name='date_purchased',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_purchased'),
        ),
        migrations.AlterField(
            model_name='prizeitem',
            name='date_taken',
            field=models.DateTimeField(blank=True, verbose_name='date_taken'),
        ),
    ]
