# Generated by Django 3.2.6 on 2021-08-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210804_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizeitem',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_taken'),
        ),
    ]
