# Generated by Django 3.2.6 on 2021-08-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_prizeitem_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=0, verbose_name='tokens'),
        ),
    ]
