# Generated by Django 3.2.6 on 2021-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tokentransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizeclass',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
