# Generated by Django 3.2.6 on 2021-08-06 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizeitem',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given', to=settings.AUTH_USER_MODEL),
        ),
    ]
