# Generated by Django 3.2.6 on 2021-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_prizeitem_given_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransfer',
            name='count',
            field=models.IntegerField(verbose_name='count'),
        ),
    ]
