# Generated by Django 3.2.6 on 2022-08-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220807_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokentransfer',
            options={'ordering': ['-created']},
        ),
    ]
