# Generated by Django 3.2.6 on 2024-08-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_tokentransfer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizeclass',
            name='auction',
            field=models.BooleanField(default=False),
        ),
    ]
