# Generated by Django 3.2.6 on 2024-08-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_prizeclass_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxprice', models.IntegerField()),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prizeclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
